#!/bin/env bash
# question 5

# Check if at least one argument is provided
if [ $# -eq 0 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# IP address to ping (the first argument)
ip_address="$1"

# Ping the IP address 5 times
ping -c 5 "$ip_address"
